"""empty message

Revision ID: 9dd1220e2f77
Revises: ce3fd22b3c72
Create Date: 2021-11-22 19:48:50.737579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dd1220e2f77'
down_revision = 'ce3fd22b3c72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkoutRecords',
    sa.Column('checkout_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=45), nullable=False),
    sa.Column('checkoutdate', sa.Date(), nullable=False),
    sa.Column('duedate', sa.Date(), nullable=False),
    sa.Column('returndate', sa.Date(), nullable=True),
    sa.Column('isbn', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['Book.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.email'], ),
    sa.PrimaryKeyConstraint('checkout_id')
    )
    op.drop_table('checkout_records')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkout_records',
    sa.Column('checkout_id', sa.INTEGER(), nullable=False),
    sa.Column('book_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=45), nullable=False),
    sa.Column('checkoutdate', sa.DATE(), nullable=False),
    sa.Column('duedate', sa.DATE(), nullable=False),
    sa.Column('returndate', sa.DATE(), nullable=True),
    sa.Column('isbn', sa.VARCHAR(length=45), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['Book.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.email'], ),
    sa.PrimaryKeyConstraint('checkout_id')
    )
    op.drop_table('checkoutRecords')
    # ### end Alembic commands ###
